### ISSUE TITLE
UV_Processed.mat for newer SMPL models

### ISSUE THREAD

**Issue by personal-coding** [Snapchat/MeshPose#3]
Is there a UV_Processed.mat file for newer SMPL models, such as SMPL-X?

**Comment by akakolyris-snap** [comment]
Thank you for your interest. We haven't experimented with SMPL-X, but to the best of our knowledge there is no densepose official UV_Processed.mat for it. It seems that there are UV maps for SMPL-X models which could be used to create this file, though. We don't have plans to work on this since it's out of the scope of our paper.
